### ISSUE TITLE
Implement 404 redirect for frontend

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/ecco#47]
So navigating directly to e.g. /about on deployed version of site properly redirects.

**Comment by falquaddoomi** [comment]
Sorry, didn't realize this was already an issue. I'd add here that this affects Netlify only.

**Comment by vincerubinetti** [comment]
You may want to have it work the same way on the prod deploy as the netlify deploys so we can catch issues. Should just have to serve the 404.html file on any route beside index.

**Comment by falquaddoomi** [comment]
I see where you're coming from in asking to make them the same, but I'm inclined not to break production so that it matches Netlify. AFAIK the correct behavior is to redirect all requests that don't match a real file back to the root so that the SPA can handle the request, not the webserver serving the SPA. The SPA can then display a 404 page if it doesn't match any known routes.

**Comment by falquaddoomi** [comment]
Oh, well, seems you've fixed it in your recent PR, so this is a non-issue anyway. Kudos!

**Comment by vincerubinetti** [comment]
Something I forgot about this, I think several months ago I told the rest of the team that the canonical production version of the site was at https://exploring-cancer-in-colorado.netlify.app (for now, I guess since it didn't require manual deployments).

I'm updating the readme to say https://ecco.cu-dbmi.dev and we can let them know.
