### ISSUE TITLE
Move locations data to backend

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/ecco#77]
Currently the data for the locations is hardcoded as geojson into the frontend (`src/api`). It should ideally be moved to the backend, even if hardcoded there, for consistency.

For the sake of automating the ingest of this data later in #74, see #19 for how the data was initially scraped and added to the frontend.

**Comment by falquaddoomi** [comment]
Hey @vincerubinetti, I've started working on this. I wanted to mention one caveat: our GIS database, PostGIS, doesn't support FeatureCollections or Features directly as geometry. Instead, you're supposed to "fully normalize" the structure by breaking out the individual elements of the FeatureCollection as tables, down to actual geometry elements (the "geometry" entry under a Feature in GeoJson), which can be stored as geometry. If you want to serve GeoJSON FeatureCollections/Features after normalizing, you do so by reconstituting that data structure when you return it from the API.

While I definitely see the benefits of fully normalizing the structure in the database, I also don't know if we'll ever need it and I would prefer to get this done quickly; we can revisit it if we find that we need it later on. Instead, I plan to store each FeatureCollection as a JSON blob in the backend, which I'd just pass off to you verbatim from the API, like how you currently load it from a JSON file in the frontend.

No action required from you, but I just wanted you to know the design decision I'm planning to take. I'm also willing to fully normalize the structure if you prefer, and I can fill you in on the pros and cons of each approach you like.

**Comment by falquaddoomi** [comment]
Ok, sounds good; I think my current implementation in #82 matches what you asked for above.

Well, the main selling point of PostGIS is that you can store geometry and perform geometric operations on it; having it parse GeoJSON and create hierarchies of tables for you isn't something it's designed to do. It's really not a lot of work for me to implement the tables (it's like 15 lines of model definition code), but since don't need to deeply index the FeatureCollection structure at the moment, I think just storing and returning it as JSON is fine.
