### ISSUE TITLE
Layout improvements, compactify

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/ecco#93]
Hey all - 

We are getting feedback regarding the legend. Folks would find it helpful to have the data source and date of source displayed on the legend. This would be be useful for those needing to use this map in a grant or presentation. Might also be useful to combine the stratification variables on the legend too so there is one box our users are pulling. Example from Cancer InFocus below:

![image](https://github.com/user-attachments/assets/7ce953e5-af9b-400f-8daf-5b01f6ec8e58)
![image](https://github.com/user-attachments/assets/c74b306e-e84a-47c5-a0e2-3d0f2795b4e7)

Let me know your thoughts on this. Thanks.

**Comment by vincerubinetti** [comment]
We can add the source and pull dates, hard-coded.

If we add that to the top left legend, though, I don't think there will be enough room for the stratification variables (the "factors" as we're calling them in the code), unless make the gradient more compact like in your screenshot, which comes at the cost of less detail.  

Shrinking the text is not really an option because it becomes an accessibility concern.

**Comment by cydneyj303** [comment]
The feedback we're getting is manly to make the legend concise with as much information as we can fit. I think it would be great to have one or two legends, just for ease for our researchers and users. Maybe we can meet to talk through this a bit more.

**Comment by vincerubinetti** [comment]
Move welcome section to top, combine with banner section. Add "click on map feature" text.

Go to horizontal scale but keep discrete, hover over block colors for value ranges.

**Comment by falquaddoomi** [comment]
For the hero, perhaps we add an extra button that either dismisses it or just scrolls the page down to the top of the map so that it becomes fullscreen? If the extra button scrolls the screen down, you might consider making the current dismiss "X" more prominent so people can dismiss it more easily.

**Comment by vincerubinetti** [comment]
@falquaddoomi Maybe "Get Started ↓` that auto-scrolls them a bit down to the map section. Auto-full-screening just the map (not the controls on the left) probably isn't desirable, but maybe you're referring to the section as a whole.

Also, will need map of measure -> source name from the backend, probably just as another top-level field on `/fips-value` like `{ ... unit, order, source: "Colorado Environmental Public Health Tracking"}`.

**Comment by falquaddoomi** [comment]
> @falquaddoomi Maybe a "Get Started ↓" button that auto-scrolls them a bit down to the map section. Auto-full-screening just the map (not the controls on the left) probably isn't desirable, but maybe you're referring to the section as a whole.

Right, I was referring to how when you scroll down to the map, it adjusts itself to fill the viewport, so just scrolling down to it to get into "map mode" should be sufficient.

> Also, will need map of measure -> source name from the backend, probably just as another top-level field on /fips-value like { ... unit, order, source: "Colorado Environmental Public Health Tracking"}.

Sounds good!

**Comment by vincerubinetti** [comment]
> Bring feature popup in front of legend, z-index

Unfortunately, due to the CSS and HTML structure of Leaftlet, this is actually not possible without a lot of dirty hacks:
https://github.com/Leaflet/Leaflet/issues/4811#issuecomment-2346614599
